# Generated by Django 5.1.1 on 2024-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(default='Remote', max_length=100)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('link_to_apply', models.URLField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
