# Generated by Django 5.1.1 on 2024-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
